import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "var(--color-background)",
        surface: "var(--color-surface)",
        "surface-2": "var(--color-surface-2)",
        foreground: "var(--color-foreground)",
        "foreground-2": "var(--color-foreground-2)",
        "muted-fg": "var(--color-muted-fg)",
        border: "var(--color-border)",
        "border-2": "var(--color-border-2)",
        primary: "var(--color-primary)",
        "primary-fg": "var(--color-primary-fg)",
        "primary-hover": "var(--color-primary-hover)",
        "primary-tint": "var(--color-primary-tint)",
        "primary-ring": "var(--color-primary-ring)",
        success: "var(--color-success)",
        "success-bg": "var(--color-success-bg)",
        "success-ring": "var(--color-success-ring)",
        warning: "var(--color-warning)",
        "warning-bg": "var(--color-warning-bg)",
        "warning-ring": "var(--color-warning-ring)",
        danger: "var(--color-danger)",
        "danger-bg": "var(--color-danger-bg)",
        "danger-ring": "var(--color-danger-ring)",
        info: "var(--color-info)",
        "info-bg": "var(--color-info-bg)",
        "info-ring": "var(--color-info-ring)",
        funeral: "var(--color-funeral)",
        "funeral-bg": "var(--color-funeral-bg)",
        automotive: "var(--color-automotive)",
        "automotive-bg": "var(--color-automotive-bg)",
        restaurant: "var(--color-restaurant)",
        "restaurant-bg": "var(--color-restaurant-bg)",
        spa: "var(--color-spa)",
        "spa-bg": "var(--color-spa-bg)",
      },
      fontFamily: {
        display: "var(--font-display)",
        sans: "var(--font-sans)",
        mono: "var(--font-mono)",
      },
      borderRadius: {
        sm: "var(--radius-sm)",
        DEFAULT: "var(--radius)",
        md: "var(--radius-md)",
        lg: "var(--radius-lg)",
        xl: "var(--radius-xl)",
      },
      boxShadow: {
        xs: "var(--shadow-xs)",
        sm: "var(--shadow-sm)",
        md: "var(--shadow-md)",
        lg: "var(--shadow-lg)",
        xl: "var(--shadow-xl)",
      },
      fontSize: {
        xs: ["0.75rem", { lineHeight: "1rem", letterSpacing: "-0.01em" }],
        sm: ["0.875rem", { lineHeight: "1.25rem", letterSpacing: "-0.01em" }],
        base: ["1rem", { lineHeight: "1.5rem", letterSpacing: "-0.01em" }],
        lg: ["1.125rem", { lineHeight: "1.75rem", letterSpacing: "-0.01em" }],
        xl: ["1.25rem", { lineHeight: "1.75rem", letterSpacing: "-0.01em" }],
        "2xl": ["1.5rem", { lineHeight: "2rem", letterSpacing: "-0.02em" }],
        "3xl": ["1.875rem", { lineHeight: "2.25rem", letterSpacing: "-0.02em" }],
        "4xl": ["2.25rem", { lineHeight: "2.5rem", letterSpacing: "-0.02em" }],
      },
    },
  },
  plugins: [],
};

export default config;
